# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/dev/mob/official/build/modorganizer_super/installer_wizard/src/ui/wizardinstallerpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WizardInstallerPage(object):
    def setupUi(self, WizardInstallerPage):
        WizardInstallerPage.setObjectName("WizardInstallerPage")
        WizardInstallerPage.resize(652, 476)
        WizardInstallerPage.setWindowTitle("")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(WizardInstallerPage)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.selectDescriptionFrame = QtWidgets.QFrame(WizardInstallerPage)
        self.selectDescriptionFrame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectDescriptionFrame.sizePolicy().hasHeightForWidth())
        self.selectDescriptionFrame.setSizePolicy(sizePolicy)
        self.selectDescriptionFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.selectDescriptionFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.selectDescriptionFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.selectDescriptionFrame.setLineWidth(1)
        self.selectDescriptionFrame.setMidLineWidth(0)
        self.selectDescriptionFrame.setObjectName("selectDescriptionFrame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.selectDescriptionFrame)
        self.verticalLayout_5.setContentsMargins(0, 2, 0, 2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.selectDescriptionLabel = QtWidgets.QLabel(self.selectDescriptionFrame)
        self.selectDescriptionLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.selectDescriptionLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.selectDescriptionLabel.setText("")
        self.selectDescriptionLabel.setWordWrap(True)
        self.selectDescriptionLabel.setObjectName("selectDescriptionLabel")
        self.verticalLayout_4.addWidget(self.selectDescriptionLabel)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout.addWidget(self.selectDescriptionFrame)
        self.optionLabel = QtWidgets.QLabel(WizardInstallerPage)
        self.optionLabel.setObjectName("optionLabel")
        self.verticalLayout.addWidget(self.optionLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.optionList = QtWidgets.QListWidget(WizardInstallerPage)
        self.optionList.setResizeMode(QtWidgets.QListView.Adjust)
        self.optionList.setObjectName("optionList")
        self.horizontalLayout_2.addWidget(self.optionList)
        self.imageLabel = QtWidgets.QLabel(WizardInstallerPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageLabel.sizePolicy().hasHeightForWidth())
        self.imageLabel.setSizePolicy(sizePolicy)
        self.imageLabel.setText("")
        self.imageLabel.setScaledContents(True)
        self.imageLabel.setObjectName("imageLabel")
        self.horizontalLayout_2.addWidget(self.imageLabel)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.descriptionLabel = QtWidgets.QLabel(WizardInstallerPage)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.verticalLayout.addWidget(self.descriptionLabel)
        self.descriptionTextEdit = QtWidgets.QTextEdit(WizardInstallerPage)
        self.descriptionTextEdit.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.descriptionTextEdit.setReadOnly(True)
        self.descriptionTextEdit.setObjectName("descriptionTextEdit")
        self.verticalLayout.addWidget(self.descriptionTextEdit)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(4, 1)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(WizardInstallerPage)
        QtCore.QMetaObject.connectSlotsByName(WizardInstallerPage)

    def retranslateUi(self, WizardInstallerPage):
        _translate = QtCore.QCoreApplication.translate
        self.optionLabel.setText(_translate("WizardInstallerPage", "Options:"))
        self.descriptionLabel.setText(_translate("WizardInstallerPage", "Description:"))
