# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/dev/mob/official/build/modorganizer_super/installer_wizard/src/ui/wizardinstallerdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WizardInstallerDialog(object):
    def setupUi(self, WizardInstallerDialog):
        WizardInstallerDialog.setObjectName("WizardInstallerDialog")
        WizardInstallerDialog.resize(769, 477)
        self.verticalLayout = QtWidgets.QVBoxLayout(WizardInstallerDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(WizardInstallerDialog)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.nameCombo = QtWidgets.QComboBox(WizardInstallerDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameCombo.sizePolicy().hasHeightForWidth())
        self.nameCombo.setSizePolicy(sizePolicy)
        self.nameCombo.setEditable(True)
        self.nameCombo.setObjectName("nameCombo")
        self.horizontalLayout_2.addWidget(self.nameCombo)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.stackedWidget = QtWidgets.QStackedWidget(WizardInstallerDialog)
        self.stackedWidget.setObjectName("stackedWidget")
        self.verticalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.manualBtn = QtWidgets.QPushButton(WizardInstallerDialog)
        self.manualBtn.setAutoDefault(False)
        self.manualBtn.setObjectName("manualBtn")
        self.horizontalLayout_3.addWidget(self.manualBtn)
        self.scriptBtn = QtWidgets.QPushButton(WizardInstallerDialog)
        self.scriptBtn.setAutoDefault(False)
        self.scriptBtn.setObjectName("scriptBtn")
        self.horizontalLayout_3.addWidget(self.scriptBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.prevBtn = QtWidgets.QPushButton(WizardInstallerDialog)
        self.prevBtn.setEnabled(False)
        self.prevBtn.setAutoDefault(False)
        self.prevBtn.setObjectName("prevBtn")
        self.horizontalLayout_3.addWidget(self.prevBtn)
        self.nextBtn = QtWidgets.QPushButton(WizardInstallerDialog)
        self.nextBtn.setObjectName("nextBtn")
        self.horizontalLayout_3.addWidget(self.nextBtn)
        self.cancelBtn = QtWidgets.QPushButton(WizardInstallerDialog)
        self.cancelBtn.setAutoDefault(False)
        self.cancelBtn.setDefault(False)
        self.cancelBtn.setFlat(False)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout_3.addWidget(self.cancelBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(WizardInstallerDialog)
        self.stackedWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(WizardInstallerDialog)

    def retranslateUi(self, WizardInstallerDialog):
        _translate = QtCore.QCoreApplication.translate
        WizardInstallerDialog.setWindowTitle(_translate("WizardInstallerDialog", "BAIN Wizard Installer"))
        self.label.setText(_translate("WizardInstallerDialog", "Name"))
        self.manualBtn.setText(_translate("WizardInstallerDialog", "Manual"))
        self.scriptBtn.setText(_translate("WizardInstallerDialog", "Script"))
        self.prevBtn.setText(_translate("WizardInstallerDialog", "Back"))
        self.nextBtn.setText(_translate("WizardInstallerDialog", "Next"))
        self.cancelBtn.setText(_translate("WizardInstallerDialog", "Cancel"))
