# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/dev/mob/official/build/modorganizer_super/tool_configurator/src/pyCfgDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PyCfgDialog(object):
    def setupUi(self, PyCfgDialog):
        PyCfgDialog.setObjectName("PyCfgDialog")
        PyCfgDialog.resize(628, 505)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pyCfg/pycfgicon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PyCfgDialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(PyCfgDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.categorySelection = QtWidgets.QComboBox(PyCfgDialog)
        self.categorySelection.setObjectName("categorySelection")
        self.horizontalLayout.addWidget(self.categorySelection)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.advancedButton = QtWidgets.QPushButton(PyCfgDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.advancedButton.sizePolicy().hasHeightForWidth())
        self.advancedButton.setSizePolicy(sizePolicy)
        self.advancedButton.setCheckable(True)
        self.advancedButton.setObjectName("advancedButton")
        self.horizontalLayout.addWidget(self.advancedButton)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.settingsTree = QtWidgets.QTreeWidget(PyCfgDialog)
        self.settingsTree.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.settingsTree.setRootIsDecorated(False)
        self.settingsTree.setColumnCount(2)
        self.settingsTree.setObjectName("settingsTree")
        self.settingsTree.header().setVisible(True)
        self.settingsTree.header().setDefaultSectionSize(270)
        self.settingsTree.header().setMinimumSectionSize(20)
        self.settingsTree.header().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.settingsTree)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.saveButton = QtWidgets.QPushButton(PyCfgDialog)
        self.saveButton.setEnabled(False)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_2.addWidget(self.saveButton)
        self.closeButton = QtWidgets.QPushButton(PyCfgDialog)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_2.addWidget(self.closeButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(PyCfgDialog)
        QtCore.QMetaObject.connectSlotsByName(PyCfgDialog)

    def retranslateUi(self, PyCfgDialog):
        _translate = QtCore.QCoreApplication.translate
        PyCfgDialog.setWindowTitle(_translate("PyCfgDialog", "Configurator"))
        self.advancedButton.setText(_translate("PyCfgDialog", "Basic"))
        self.settingsTree.headerItem().setText(0, _translate("PyCfgDialog", "Key"))
        self.settingsTree.headerItem().setText(1, _translate("PyCfgDialog", "Value"))
        self.saveButton.setText(_translate("PyCfgDialog", "Save"))
        self.closeButton.setText(_translate("PyCfgDialog", "Close"))
import pyCfgResource_rc
